individual_args:
  model_name: lenet

problem_args:
  problem_name: MNIST
  batch_size: 50000
  eval_batch_size: 10000

ga_args:
  population_size: 200
  num_parents: 200
  crossover: uniform
  selection: weighted
  mutation: uniform
  mutation_chance: 0.01
  elitism: 0.
  parent_survival_rate: 0.5
  generations: 100
  eval_every_generation: 1000

sys_args:
  device: cuda

output_dir:
  root: ../experiments   # creates this root directory for the outputs
  name: mnist            # the name of the experiment (optional)