individual_args:
  model_name: dqn
  individual_name: rl

problem_args:
  problem_name: cartpole
  batch_size: -1
  eval_batch_size: -1
  steps: 10
  runs: 5
  stop_on_done: False

ga_args:
  population_size: 100
  num_parents: 100
  crossover: uniform
  selection: weighted
  mutation: uniform
  mutation_chance: 0.01
  elitism: 0.
  parent_survival_rate: 0.5
  generations: 100
  eval_every_generation: 1000

sys_args:
  device: cuda

output_dir:
  root: ../experiments   # creates this root directory for the outputs
  name: mnist            # the name of the experiment (optional)